### ISSUE TITLE
Service doesn’t recognize renamed file

### ISSUE THREAD

**Issue by JensSpanier** [OptiSchmopti/CsvProc9000#33]
Chrome saves files by adding the extension `.crdownload` to the file and renaming it to the original filename after finishing the download.

The service doesn’t recognize this file.

**Comment by wgnf** [comment]
just a heads up:  
will probably resolve this "issue" this weekend. maybe earlier, depending on my time & mood ;)

**Comment by wgnf** [comment]
also: i wouldn't necessarily call this a bug. Detecting files works, detecting files that have been renamed in _that_ directory is a new feature imo

**Comment by JensSpanier** [comment]
> also: i wouldn't necessarily call this a bug. Detecting files works, detecting files that have been renamed in _that_ directory is a new feature imo

In my opinion it depends on the point of view.
From a developers point of view – yes, this is a feature.
From customer’s point of view – the customer is saving a file from the web and the service doesn’t recognizes it. So the customer would call it a bug.

**Comment by wgnf** [comment]
yeah you're right about this one, let's just call it a `bughancement` 🌚
